# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' parse_rmd
#'
#' @noRd
rcpp_parse_rmd <- function(filename, tempfile) {
    invisible(.Call(`_srr_rcpp_parse_rmd`, filename, tempfile))
}

